# Site
name: "Tung's blog"
title: "Tung's blog"
description: "A data engineer, vim user, table tennis lover"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/my-blog' 
google_analytics: ''
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Tung:
    name: Dao Thanh Tung 
    display_name: Dao Thanh Tung 
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: dttung2905@gmail.com
    web: https://dttung2905.github.io/my-blog/ 
    twitter: https://twitter.com/wowthemesnet
    description: "Blogging for fun"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
